version: '3.7'
services:
  jenkins:
    networks:
      - test
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker


  sonarqube:
    image: sonarqube:lts
    ports:
      - 9000:9000
    networks:
      - test

networks:
    test:
        #driver: bridge  #Use this when you have not created a network beforehand
        external: true